#!/usr/bin/env nu
# Read-only inventory of the secret files the framework owns, across both roots (the runtime secrets dir
# and the OIDC credentials dir). The manifest is generated from the same options the generators read, so
# a declared owner/mode is the value that was applied and a mismatch on disk is real drift.
let manifest = (open $env.HOMELAB_SECRETS_MANIFEST)

# Leading-zero pad so a mode written "400" compares equal to one written "0400": `stat` never pads,
# and the option is a free-form string.
def pad_mode [mode: string] { $mode | fill -a r -w 4 -c "0" }

# Absent and unreadable are different answers. A 0700 parent (notify-publishers) denies an unprivileged
# stat, and reporting that as missing would say a secret is gone while it sits there.
def inspect [entry: record] {
  let r = (^stat -c "%U:%G %a" $entry.path | complete)
  if $r.exit_code != 0 {
    let status = if ($r.stderr | str contains "Permission denied") { "unknown" } else { "missing" }
    return { status: $status, actual: "", expected: "" }
  }
  let parts = ($r.stdout | str trim | split row " ")
  let actual = $"($parts | get 0) (pad_mode ($parts | get 1))"
  if $entry.expected == null {
    return { status: "ok", actual: $actual, expected: "" }
  }
  let expected = $"($entry.expected.owner):($entry.expected.group) (pad_mode $entry.expected.mode)"
  if $actual == $expected {
    # Matching, so `actual` already shows the declared value and repeating it would only widen the table.
    return { status: "ok", actual: $actual, expected: "" }
  }
  { status: "drift", actual: $actual, expected: $expected }
}

def inspected [] { $manifest | each {|e| $e | merge (inspect $e) } }

def rollup [entries: list] {
  let bad = ($entries | where status != "ok")
  if ($bad | is-empty) { return "ok" }
  $bad | group-by status | transpose status items | each {|g| $"($g.items | length) ($g.status)" } | str join ", "
}

# Rendered here rather than returned as data, to drop nushell's row-index column: it is noise in a
# listing whose rows are addressed by name. The width is explicit because `term size` reports 0 with no
# terminal — over a pipe or in a test — and `table` then refuses to draw anything at all.
def render [] {
  # Bound first: the `term size` call below would otherwise consume the pipeline input.
  let rows = $in
  let width = (term size | get columns)
  $rows | table --index false --width (if $width < 40 { 100 } else { $width })
}

def detail [entries: list, long: bool] {
  if $long {
    $entries
    | select name kind status actual expected
    | rename NAME KIND STATUS "OWNER:MODE" EXPECTED
    | render
  } else {
    $entries | select name kind status | rename NAME KIND STATUS | render
  }
}

def missing_hint [entry: record] {
  if $entry.unit == null {
    "Nothing on this host generates it. Restore it from your own store."
  } else {
    $"Generated by ($entry.unit). Check `journalctl -u ($entry.unit)`."
  }
}

# No argument lists the apps holding secrets, so you can find one without knowing a name. An argument
# matches app and name alike: `ls radicale` reads as drilling into a group, `ls alice` crosses groups
# and finds every secret belonging to one person.
def "main ls" [
  filter?: string # text to match against app and secret name
  --long (-l)     # show actual and declared ownership
] {
  let all = (inspected)
  if $filter == null {
    if $long { return (detail ($all | sort-by app name) true) }
    $all
    | group-by app
    | transpose app entries
    | each {|g| { APP: $g.app, SECRETS: ($g.entries | length), STATUS: (rollup $g.entries) } }
    | sort-by APP
    | render
  } else {
    let needle = ($filter | str lowercase)
    let hits = (
      $all | where {|e|
        ($e.name | str lowercase | str contains $needle) or ($e.app | str lowercase | str contains $needle)
      }
    )
    if ($hits | is-empty) {
      print --stderr $"No secret matches '($filter)'. Run `homelab-secrets ls` to see the apps."
      return
    }
    detail ($hits | sort-by app name) $long
  }
}

def "main cat" [name: string] {
  let entry = ($manifest | where name == $name | get -o 0)
  if $entry == null {
    error make --unspanned {msg: $"Unknown secret '($name)'. Run `homelab-secrets ls` to see what exists."}
  }
  if (inspect $entry).status == "missing" {
    error make --unspanned {msg: $"'($name)' is not on disk. (missing_hint $entry)"}
  }
  if (^test -r $entry.path | complete).exit_code != 0 {
    error make --unspanned {msg: $"'($name)' is not readable by you. Re-run with sudo."}
  }
  # `^cat`, not `open`: `open` parses by extension, so a template named `.json` would come back a table.
  # Passing the bytes through untouched also makes `$(homelab-secrets cat x)` behave like `$(sudo cat …)`.
  ^cat $entry.path
}

def main [] {
  print "homelab-secrets — inspect framework-managed secrets (read-only)"
  print ""
  print "  ls                 apps holding secrets, with status"
  print "  ls <text>          secrets matching <text>, in app or name"
  print "  ls -l              every secret, with actual and declared ownership"
  print "  cat <name>         print one secret (needs root)"
  print ""
  print "  homelab-secrets ls radicale"
  print "  sudo homelab-secrets cat radicale-password-alice"
}
