# Per-principal SMB surface, shared by `selfhost.users` and `selfhost.serviceAccounts`. Holding an
# account is separate from being let into a share: grants live on the share.
{ name, lib, ... }:
let
  secretsDir = "/var/lib/homelab-secrets"; # persistent, see runtime-secrets.nix
in
{
  options.storage.smb = {
    enable = lib.mkEnableOption "an SMB account for this principal on a host serving `selfhost.storage.shares.smb`";

    passwordFile = lib.mkOption {
      type = lib.types.str;
      default = "${secretsDir}/smb-password-${name}";
      defaultText = lib.literalMD "a password generated for this principal under `runtimeSecretsDir`";
      description = "File holding this principal's SMB password, read at activation through a credential and never placed in the store. Generated by default, like Radicale's and CouchDB's: a person types it into a device once, so nobody needs to pick it. Set it instead when the same value has to exist somewhere else too, as for a machine principal whose client reads it from your own secret store: generating here would leave you hand-copying it there.";
    };
  };
}
